### ISSUE TITLE
Прив'язати парламентські порушення до скликання

### ISSUE THREAD

**Issue by zefmud** [chesnolabs/chesno#101]
Прив'язати порушення таких типів:
- біографію на звернення не надано
- декларацію приховано
- приймальні народного депутата приховано
- помічників народного депутата приховано
- надано неповний список
- незмінність політичної позиції  
... до скликання, в якому особа була народним депутатом. На разі вони виводяться на чинних депутатах, навіть якщо вони порушували у 7 скликанні. 
![khomutynnik_vr8](https://cloud.githubusercontent.com/assets/7829010/7346932/f022a2fe-eceb-11e4-92e6-883352f91a50.PNG)

**Comment by gud123** [comment]
"приховування декларації" прив’язувати вважаю недоцільним.
по іншому згоден, варто додати поле скликання.

Інт:

1)Терміново - прибрати з 8 скликання усі порушення, окрім декларації та неособистого голосування.
2)Додати в усі порушення поле Парламент, як у "Неособистого голосування", залишити його необов’язковим для заповнення.
3)Штурхнути мене, щоб придумати, як заповнювати ці поля.

**Comment by int-ua** [comment]
Поганий багрепорт, нічого одразу не ясно.

**Comment by int-ua** [comment]
Отже:
1) Додаємо поле "Скликання" у порушеннях. Ще треба обдумати чи не прибрати поле "Депутат".
0) Порушення з OP крім приховання декларації показувати виключно у профілях 7 скликання.

**Comment by int-ua** [comment]
0) Зробив, але далеко не у всіх порушеннях вибраний депутат, тобто з 7-го скликання вони зараз теж щезли.

**Comment by int-ua** [comment]
Продовження у #105
