### ISSUE TITLE
API з http://declarations.com.ua/

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#103]
1)оцінити можливості інтеграції їх даних в нашу БД 
2)разом зі Змієм та Сергієм Б. оцінити чи буде напряжно інтегрувати з лого декларацій.

**Comment by int-ua** [comment]
лого?

**Comment by gud123** [comment]
ну або лінк на їх сайт або якийсь логотип канцелярської  сотні, хз, будемо по ходу з’ясовувати (;

**Comment by int-ua** [comment]
ага, з додаванням лого, ясно
