### ISSUE TITLE
Видалення окремого елементу з галереї інфографіки

### ISSUE THREAD

**Issue by Karmilhan** [chesnolabs/chesno#107]
Під час видалення одного зображення з галереї інфографіки видаляється уся галерея.

**Comment by int-ua** [comment]
O_O

**Comment by int-ua** [comment]
Не можу відтворити у себе. Видалив фото, галерея є. Як саме ти видаляв фото?

**Comment by Karmilhan** [comment]
Обрав один з елементів (http://clip2net.com/s/3hBo52W) і натиснув кнопку "Видалити".
До речі, фото з видаленої галереї поки ще доступні за старими адресами.

**Comment by int-ua** [comment]
Червону кнопку "Видалити" у нижньому лівому кутку? Фух :) Це вже панель керування усією галереєю.

**Comment by Karmilhan** [comment]
Логіка інтерфейсу неочевидна. Я міркував так: обираєш хрестиком одне з фото, а потім підтверджуєш кнопкою, мовляв, так, видалити. Можна змінити напис на кнопці "Видалити усю галерею", аби уникнути непорозумінь.

**Comment by int-ua** [comment]
Ну про усю галерею є у тексті попередження ж.

**Comment by int-ua** [comment]
Додав на кнопку назву об’єкту, що буде видалено.
