### ISSUE TITLE
Профіль депутатів - Депутатські звіти

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#119]
1.Створити у профілях депутатів 8 скликання на http://www.chesno.org/vr8/deputy/1825/ - Блок Депутатські звіти.
2. У блоці - лайтбокс або аналог для перегляду на сторінці (без переходу на новий) pdf файлів (до 10 сторінок).
3. Імпортувати дані (чекай листа від Павла).

**Comment by zefmud** [comment]
документ с файлами здесь: https://drive.google.com/open?id=0B1YT04hZXp_KN0lrbGQxWUtSLVU
Файл прислал в теме "документ с названиями файлов отчетов"

**Comment by int-ua** [comment]
Перенесено.
