### ISSUE TITLE
Admin - Violations

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#12]
https://chesno.org/admin/person/violation/1216/

біля пункту "фото" хотілося б мати можливість вказувати посилання, а не тільки завантажувати фото.

**Comment by int-ua** [comment]
Посилання на відео десь використовується саме як відео? Чи може перетворити це поле на "Посилання на доказ на сторонньому ресурсі"?

**Comment by gud123** [comment]
це практично завжди посилання на YouTube

**Comment by int-ua** [comment]
Питання у тому, чи є десь код, який очікує саме виключно посилання на youtube? Чи як мінімум завжди посилання на відео? Чи можна розширити його призначення?

**Comment by gud123** [comment]
може в новинах https://chesno.org/admin/press/
та Відео https://chesno.org/admin/gallery/video/
щодо специфічного коду - це Рома має знати (;

12 березня 2015 р. 17:12 Serhiy Zahoriya <notifications@github.com> написав:

> Питання у тому, чи є десь код, який очікує саме виключно посилання на
> youtube? Чи як мінімум завжди посилання на відео? Чи можна розширити його
> призначення?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chesnolabs/chesno/issues/12#issuecomment-78499594>.
>



-- 
Усього найкращого!

Вадим Гудима
редактор chesno.org
068 238 44 30
