### ISSUE TITLE
Головна - Кандидати (Пошук): При неправильному прізвищі + Enter -> 404

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#44]
Головна - Кандидати (Пошук): При неправильному прізвищі + Enter -> 404
Бажана реакція(приклад):
Pop-up з повідомленням про помилку та пропозицію набрати інше або коротше прізвище?

Антоне, можеш щось притомне по дизайну підібрати/намалювати?

**Comment by gud123** [comment]
Кушнііір?

**Comment by Karmilhan** [comment]
Давно прислав Гудимі
