### ISSUE TITLE
JSON - номери скликань депутатам

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#58]
від macpaw: Пропонуємо додати до кожного депутата у JSON масив номерів скликань (напр. 7, 8), а ми на своїй стороні будемо їх фільтрувати. Так як депутатів не так і багато, то пока краще всіх одразу завантажувати на старті.

**Comment by suprotkin** [comment]
http://chesno.org/persons/json/deputies/all/ - всі депи
http://chesno.org/persons/json/deputies/8/ - восьме скликання

**Comment by gud123** [comment]
напиши плз як буде готове в гілку макпав Declarations App, щоб я не був
зіпсутим телефоном (;

неясно щодо 7 скликання


2015-01-12 8:36 GMT+02:00 Roman Suprotkin <notifications@github.com>:

> http://chesno.org/persons/json/deputies/all/ - всі депи
> http://chesno.org/persons/json/deputies/8/ - восьме скликання
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chesnolabs/chesno/issues/58#issuecomment-69533880>.
>



-- 
Усього найкращого!

Вадим Гудима
редактор chesno.org
068 238 44 30

**Comment by suprotkin** [comment]
http://chesno.org/persons/json/deputies/7/
Можна уже показувати
