### ISSUE TITLE
Логотипи на фото

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#68]
Можливість автоматично проставляти логотип ЧЕСНО на фотоматеріали на нашому сайті.

**Comment by int-ua** [comment]
На усі без виключень чи на вибір авторів?

**Comment by gud123** [comment]
на вибір авторів. пріоритет завтра виставлю

2015-03-11 23:22 GMT+02:00 Serhiy Zahoriya <notifications@github.com>:

> На усі без виключень чи на вибір авторів?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chesnolabs/chesno/issues/68#issuecomment-78374844>.
>



-- 
Усього найкращого!

Вадим Гудима
редактор chesno.org
068 238 44 30

**Comment by int-ua** [comment]
https://django-filebrowser.readthedocs.org/en/latest/admin.html#custom-actions
