### ISSUE TITLE
Локалізація неповна

### ISSUE THREAD

**Issue by int-ua** [chesnolabs/chesno#69]
Як мінімум на http://chesno.org/en/data/ не вистачає перекладу.

**Comment by gud123** [comment]
це по купі елементів проблема, одна з причин чому я вирішив робити окремо
сайт, окремо сторінки-інструменти - локалізацію сайту ще реально зробити, а
от всі дані перекладати - unreal

14 березня 2015 р. 22:02 Serhiy Zahoriya <notifications@github.com> написав:

> Як мінімум на http://chesno.org/en/data/ не вистачає перекладу.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chesnolabs/chesno/issues/69>.
>



-- 
Усього найкращого!

Вадим Гудима
редактор chesno.org
068 238 44 30
