### ISSUE TITLE
Не перенесено відображення розділів у профілі депутатів з Person

### ISSUE THREAD

**Issue by zefmud** [chesnolabs/chesno#70]
У профілях депутатів 8 скликання не відображаються дані про їхні приймальні.
Наприклад, Герега:
https://chesno.org/admin/deputy/publicoffice/?q=%D0%B3%D0%B5%D1%80%D0%B5%D0%B3%D0%B0
http://chesno.org/vr8/deputy/2145/
Або Борислав Береза:
https://chesno.org/admin/deputy/publicoffice/?q=%D0%B1%D0%B5%D1%80%D0%B5%D0%B7%D0%B0
http://chesno.org/vr8/deputy/2075/

**Comment by int-ua** [comment]
Трохи розібрався, треба буде з Person перенести код у Deputy.
