### ISSUE TITLE
Баг із завантажувачем картинок

### ISSUE THREAD

**Issue by Karmilhan** [chesnolabs/chesno#71]
Картинки не вантажаться ні в мене, ні у Федорів

**Comment by int-ua** [comment]
Це про те, що англійською upload і у деяких колах перекладають "вивантажувати"?

**Comment by int-ua** [comment]
У журналі помилок ніби нічого про це. Чекаю більш детального опису.

**Comment by Karmilhan** [comment]
За кліком на кнопку не відкривається менюшка завантаження файлів на сервер: http://clip2net.com/s/3esdQDj

**Comment by int-ua** [comment]
Спробуй.
