### ISSUE TITLE
лапки у URL сприймаються не усіма переглядачами

### ISSUE THREAD

**Issue by int-ua** [chesnolabs/chesno#72]
Здається, не генеруються мініатюри до файлів, що містять лапки/апостроф. Треба потім перевірити.
Суджу з таких помилок у журналі:

    project/media/media/persons/24392_rybchyns&" failed (2: No such file or directory)

**Comment by int-ua** [comment]
Те ж саме з деклараціями

**Comment by int-ua** [comment]
Відслідкував одну таку помилку, у мене фото показується. В UserAgent у журналі - UCBrowser/9.8.0.435. Хоча percent-encode кавички у URL було б непогано, треба перевірити, чи додано це у новішій версії (якщо вона існує) того, що зараз лежить у `lib/thumbs.py’.

**Comment by suprotkin** [comment]
Май на увазі, що моя версія патчена
23 бер. 2015 10:02, користувач "Serhiy Zahoriya" <notifications@github.com>
написав:

**Comment by int-ua** [comment]
Перенесено.
