### ISSUE TITLE
Немає фракцій у 7 скликанні

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#74]
http://awesomescreenshot.com/0304p5810b

**Comment by suprotkin** [comment]
А прі камуністах такова нєбило!

**Comment by int-ua** [comment]
AFAIK, вибираються тільки діючі фракції ж) Ну і те, що фракції 7 скликання лишались активними... Ні?

**Comment by int-ua** [comment]
Помітив от випадково.
