### ISSUE TITLE
Прив’язка приймалень до округу

### ISSUE THREAD

**Issue by zefmud** [chesnolabs/chesno#93]
Потрібно прибрати прив’язку приймальні до округу, принаймні як обов’язкове поле. Потрібно також додати поле "Область", оскільки зараз прив’язка до області відбувається лише через округ.

**Comment by int-ua** [comment]
Пропоную зміни структури БД попередньо обговорювати вживу все ж.

**Comment by zefmud** [comment]
вчора чуть-чуть обговорили, гудима попросив його зробить за це відповідальним.

**Comment by gud123** [comment]
угу, я хочу над цим помедитувати, враховуючи проблему регіонів, яка перед
нами стоїть (;

8 квітня 2015 р. 13:06 zefmud <notifications@github.com> написав:

> вчора чуть-чуть обговорили, гудима попросив його зробить за це
> відповідальним.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chesnolabs/chesno/issues/93#issuecomment-90868963>.
>



-- 
Усього найкращого!

Вадим Гудима
редактор chesno.org
068 238 44 30

**Comment by int-ua** [comment]
Ем. https://github.com/chesnolabs/chesno/issues/73
