### ISSUE TITLE
Приймальні - for download

### ISSUE THREAD

**Issue by gud123** [chesnolabs/chesno#96]
Генерувати з бази та виводити на фронтенд документ для скачування з прізвищами депутатів, адресами приймалень, їх координатами, графіком роботи, телефонами, факсами, додатковою інформацією.

Паша - сформувати бажаний для end-user вигляд та формат документа.
Інт - ну ти в курсі, і мої співчуття ((;

**Comment by zefmud** [comment]
1.	Person_ID
2.	Повне ім’я депутата.
3.	Округ (за наявністю чи за автоматичним визначенням)
4.	Область
5.	Адреса
6.	Координати
7.	Телефон
8.	Факс
9.	Час роботи
10.	Extra
11.	Активність (true/false)
12.	Дата останнього оновлення

**Comment by zefmud** [comment]
Це був список полів для виведення.
